//! Property tests.
//!
//! The unit tests in each module check specific, chosen inputs. These check
//! that the invariants hold across randomly generated ones — which is where
//! encoding and edge-case bugs actually live.

use ark_ff::UniformRand;
use proptest::prelude::*;
use rapido_core::{dst, Epoch};
use rapido_crypto::{
    bbs, bls, elgamal, kdf, pedersen, relation, rng_from_seed, ser, shamir, Fr, G1Projective,
};
use std::collections::BTreeSet;

/// Derive a scalar deterministically from a proptest-supplied seed, so cases
/// shrink to reproducible values.
fn scalar(seed: u64) -> Fr {
    Fr::rand(&mut rng_from_seed(seed))
}

proptest! {
    #![proptest_config(ProptestConfig { cases: 48, ..ProptestConfig::default() })]

    /// derive -> sign -> verify, over arbitrary keys, epochs, and messages.
    #[test]
    fn derive_sign_verify_round_trip(
        master in any::<[u8; 32]>(),
        epoch in 0u64..1_000_000,
        counter in 0u32..100_000,
        msg in proptest::collection::vec(any::<u8>(), 0..512),
    ) {
        let ms = kdf::MasterSecret(master);
        let sk = bls::SecretKey(kdf::derive_scalar(&ms, Epoch(epoch), counter));
        let sig = bls::sign(&sk, dst::PRESENT, &msg);
        prop_assert!(bls::verify(&sk.public(), dst::PRESENT, &msg, &sig).is_ok());

        // Re-deriving the same (epoch, counter) must give the same key.
        let again = bls::SecretKey(kdf::derive_scalar(&ms, Epoch(epoch), counter));
        prop_assert_eq!(sk.0, again.0);
    }

    /// A signature must not verify under a different message.
    #[test]
    fn signature_does_not_verify_on_a_different_message(
        seed in any::<u64>(),
        a in proptest::collection::vec(any::<u8>(), 0..128),
        b in proptest::collection::vec(any::<u8>(), 0..128),
    ) {
        prop_assume!(a != b);
        let sk = bls::SecretKey(scalar(seed));
        let sig = bls::sign(&sk, dst::PRESENT, &a);
        prop_assert!(bls::verify(&sk.public(), dst::PRESENT, &b, &sig).is_err());
    }

    /// Point and scalar serialization round-trips, and rejects truncation.
    #[test]
    fn serialization_round_trips(seed in any::<u64>()) {
        let mut rng = rng_from_seed(seed);
        let sk = bls::SecretKey::random(&mut rng);
        let pk = sk.public();
        let sig = bls::sign(&sk, dst::CRED, b"m");

        prop_assert_eq!(bls::PublicKey::from_bytes(&pk.to_bytes()).unwrap(), pk);
        prop_assert_eq!(bls::Signature::from_bytes(&sig.to_bytes()).unwrap(), sig);

        let s = Fr::rand(&mut rng);
        prop_assert_eq!(ser::fr_from_bytes(&ser::fr_to_bytes(&s), "t").unwrap(), s);

        // Truncated input must fail closed rather than parse a shorter point.
        let b = pk.to_bytes();
        prop_assert!(bls::PublicKey::from_bytes(&b[..b.len() - 1]).is_err());
    }

    /// Any bit flip in a serialized point either fails to parse or decodes to a
    /// different point — never silently to the same one.
    #[test]
    fn bit_flips_never_decode_to_the_original_point(
        seed in any::<u64>(),
        bit in 0usize..(48 * 8),
    ) {
        let mut rng = rng_from_seed(seed);
        let pk = bls::SecretKey::random(&mut rng).public();
        let mut b = pk.to_bytes();
        b[bit / 8] ^= 1u8 << (bit % 8);
        match bls::PublicKey::from_bytes(&b) {
            Err(_) => {}
            Ok(other) => prop_assert_ne!(other, pk),
        }
    }

    /// Shamir: any `k` of `n` shares reconstruct; the sharing is deterministic
    /// in the RNG.
    #[test]
    fn shamir_reconstructs_from_any_k_shares(
        seed in any::<u64>(),
        k in 1usize..6,
        extra in 0usize..5,
        pick in proptest::collection::vec(any::<u8>(), 6),
    ) {
        let n = k + extra;
        let mut rng = rng_from_seed(seed);
        let secret = Fr::rand(&mut rng);
        let shares = shamir::split(secret, k, n, &mut rng).unwrap();
        prop_assert_eq!(shares.len(), n);

        // Choose an arbitrary k-subset driven by the generated bytes.
        let mut idx: Vec<usize> = (0..n).collect();
        for (i, byte) in pick.iter().enumerate().take(n) {
            let j = (*byte as usize) % n;
            idx.swap(i.min(n - 1), j);
        }
        let subset: Vec<shamir::Share> = idx[..k].iter().map(|i| shares[*i]).collect();
        prop_assert_eq!(shamir::reconstruct(&subset, k).unwrap(), secret);
    }

    /// Threshold BLS: any `k` partial signatures combine to a signature that
    /// verifies under the group key.
    #[test]
    fn threshold_bls_combines_from_any_k(
        seed in any::<u64>(),
        k in 1usize..5,
        extra in 0usize..4,
        msg in proptest::collection::vec(any::<u8>(), 0..64),
    ) {
        let n = k + extra;
        let mut rng = rng_from_seed(seed);
        let tk = bls::ThresholdKey::generate(k, n, &mut rng).unwrap();
        let partials: Vec<bls::PartialSignature> =
            tk.shares.iter().map(|s| bls::partial_sign(s, dst::CRED, &msg)).collect();
        let sig = bls::combine(&partials[..k], k).unwrap();
        prop_assert!(bls::verify(&tk.group_public, dst::CRED, &msg, &sig).is_ok());
    }

    /// Pedersen commitments are binding under the openings we produce and
    /// hiding across blinding factors.
    #[test]
    fn pedersen_round_trip(seed in any::<u64>(), value in any::<u64>()) {
        let mut rng = rng_from_seed(seed);
        let p = pedersen::Params::default();
        let v = Fr::from(value);
        let (c, o) = p.commit_random(v, &mut rng);
        prop_assert!(p.verify_opening(&c, &o));
        prop_assert_eq!(pedersen::Commitment::from_bytes(&c.to_bytes()).unwrap(), c);

        let (c2, _) = p.commit_random(v, &mut rng);
        prop_assert_ne!(c, c2);
    }

    /// A Schnorr linear-relation proof verifies iff it is checked against the
    /// statement and context it was made for.
    #[test]
    fn linear_proof_round_trip(
        seed in any::<u64>(),
        ctx in proptest::collection::vec(any::<u8>(), 0..64),
    ) {
        let mut rng = rng_from_seed(seed);
        let g = <G1Projective as ark_ec::PrimeGroup>::generator();
        let x = Fr::rand(&mut rng);
        let rel = relation::schnorr_relation(g, g * x);
        let p = rel.prove(dst::SCHNORR, &[x], &ctx, &mut rng).unwrap();
        prop_assert!(rel.verify(dst::SCHNORR, &p, &ctx).is_ok());
        prop_assert_eq!(relation::LinearProof::from_bytes(&p.to_bytes()).unwrap(), p.clone());

        let mut other = ctx.clone();
        other.push(0xff);
        prop_assert!(rel.verify(dst::SCHNORR, &p, &other).is_err());
    }

    /// BBS+: sign, present with an arbitrary disclosure set, verify.
    #[test]
    fn bbs_presentation_round_trip(
        seed in any::<u64>(),
        l in 1usize..10,
        mask in any::<u16>(),
        nonce in proptest::collection::vec(any::<u8>(), 0..48),
    ) {
        let mut rng = rng_from_seed(seed);
        let params = bbs::Params::new(l);
        let sk = bbs::SecretKey::random(&mut rng);
        let pk = sk.public();
        let msgs: Vec<Fr> =
            (0..l).map(|i| bbs::message_from_bytes(&[i as u8, seed as u8])).collect();
        let sig = bbs::sign(&params, &sk, &msgs, &mut rng).unwrap();
        prop_assert!(bbs::verify(&params, &pk, &msgs, &sig).is_ok());

        let disclose: BTreeSet<usize> =
            (0..l).filter(|i| mask & (1u16 << (i % 16)) != 0).collect();
        let pres =
            bbs::present(&params, &pk, &msgs, &sig, &disclose, &nonce, None, &mut rng).unwrap();
        let got = bbs::verify_presentation(&params, &pk, &pres, &nonce, None).unwrap();
        prop_assert_eq!(got.len(), disclose.len());
        for i in &disclose {
            prop_assert_eq!(got[i], msgs[*i]);
        }
        prop_assert_eq!(bbs::Signature::from_bytes(&sig.to_bytes()).unwrap(), sig);
    }

    /// Threshold ElGamal: encrypt, partially decrypt with `k` shares, recover.
    #[test]
    fn threshold_elgamal_round_trip(
        seed in any::<u64>(),
        k in 1usize..5,
        extra in 0usize..4,
        id in proptest::collection::vec(any::<u8>(), 1..32),
    ) {
        let n = k + extra;
        let mut rng = rng_from_seed(seed);
        let key = elgamal::EscrowKey::generate(k, n, &mut rng).unwrap();
        let scalar = elgamal::identity_scalar(&id);
        let m = elgamal::identity_point(scalar);
        let (ct, _r) = elgamal::encrypt(key.public, m, &mut rng);
        prop_assert_eq!(elgamal::Ciphertext::from_bytes(&ct.to_bytes()).unwrap(), ct);

        let partials: Vec<elgamal::PartialDecryption> =
            key.shares.iter().map(|s| elgamal::partial_decrypt(s, &ct)).collect();
        prop_assert_eq!(elgamal::combine_decryptions(&partials[..k], &ct, k).unwrap(), m);
    }

    /// E2 accepts an honest attachment and rejects one built for a different
    /// identity, for arbitrary identities.
    #[test]
    fn escrow_proof_binds_to_the_committed_identity(
        seed in any::<u64>(),
        honest in proptest::collection::vec(any::<u8>(), 1..24),
        other in proptest::collection::vec(any::<u8>(), 1..24),
    ) {
        prop_assume!(honest != other);
        let mut rng = rng_from_seed(seed);
        let ped = pedersen::Params::default();
        let key = elgamal::EscrowKey::generate(2, 3, &mut rng).unwrap();
        let id = elgamal::identity_scalar(&honest);
        let (commitment, opening) = ped.commit_random(id, &mut rng);
        let (ct, r) = elgamal::encrypt(key.public, elgamal::identity_point(id), &mut rng);

        let proof = elgamal::prove_correct_encryption(
            &ped, key.public, &ct, &commitment, id, r, opening.blinding, b"ctx", &mut rng,
        )
        .unwrap();
        prop_assert!(
            elgamal::verify_correct_encryption(&ped, key.public, &ct, &commitment, &proof, b"ctx")
                .is_ok()
        );

        // A ciphertext for a different identity has no valid proof against the
        // same commitment.
        let (wrong_ct, _) = elgamal::encrypt(
            key.public,
            elgamal::identity_point(elgamal::identity_scalar(&other)),
            &mut rng,
        );
        prop_assert!(
            elgamal::verify_correct_encryption(
                &ped, key.public, &wrong_ct, &commitment, &proof, b"ctx"
            )
            .is_err()
        );
    }
}
