[package]
name = "rapido-proto"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true

[dependencies]
rapido-core = { workspace = true }
rapido-crypto = { workspace = true }
ark-bls12-381 = { workspace = true }
ark-ec = { workspace = true }
ark-ff = { workspace = true }
sha2 = { workspace = true }
rand = { workspace = true }
serde = { workspace = true }
hex = { workspace = true }

[dev-dependencies]
proptest = { workspace = true }
serde_json = { workspace = true }
