#!/usr/bin/env python3
"""Emit the LaTeX tables from the committed result files.

No reported number is typed by hand: a document `\\input`s these files. Running
this script is the only supported way to update a table.
"""

from __future__ import annotations

import sys

import common
import pandas as pd


def fmt_ci(row) -> str:
    """Median with its interval, both at three significant figures.

    Not more: the measurement machine's metadata records that its clock
    frequency is not controllable, so a tighter quote claims precision the
    platform cannot deliver.
    """
    med, lo, hi = row["median_ms"], row["ci95_lo_ms"], row["ci95_hi_ms"]
    if med < 0.001:
        return f"{common.sig3(med * 1000)}\\,\\textmu s"
    return f"{common.sig3(med)} [{common.sig3(lo)}, {common.sig3(hi)}]"


def table1(df: pd.DataFrame) -> str:
    rows = [
        ("RAPIDO Mode A", "naive, no escrow \\textbf{(fastest)}", "mode-a-verify-naive",
         {"escrow": "e0"}),
        ("RAPIDO Mode A", "aggregate, no escrow", "mode-a-verify-aggregate", {"escrow": "e0"}),
        ("RAPIDO Mode A", "aggregate + E2 escrow", "mode-a-verify-full-pipeline", {"escrow": "e2"}),
        ("RAPIDO Mode B", "$L=8$, all hidden", "mode-b-verify",
         {"L": 8, "disclosure_fraction": 0.0, "escrow": "e0"}),
        ("RAPIDO Mode B", "$L=8$, all hidden + E2", "mode-b-verify",
         {"L": 8, "disclosure_fraction": 0.0, "escrow": "e2"}),
        ("mTLS-like", "Ed25519, chain depth 2", "mtls-ed25519-verify", {}),
        ("mTLS-like", "ECDSA P-256, chain depth 2", "mtls-p256-verify", {}),
        ("SCMS (IEEE 1609.2)", "explicit certificate", "scms-explicit-verify", {}),
        ("SCMS (IEEE 1609.2)", "implicit (ECQV)", "scms-implicit-verify", {}),
        ("Idemix-like", "CL-RSA-2048, $L=5$", "cl-rsa-verify", {"L": 5, "n_disclosed": 0}),
    ]
    out = ["% Generated by analysis/gen_tables.py. Do not edit by hand.",
           "\\begin{tabular}{llllr}", "\\toprule",
           "System & Variant & Profile & Verify (ms, median [95\\% CI]) & Wire (B) \\\\",
           "\\midrule"]
    for system, variant, name, cond in rows:
        for profile, sub in df.groupby("profile"):
            hit = common.select(sub[sub["name"] == name], **cond)
            if hit.empty:
                continue
            r = hit.iloc[0]
            wire = "--" if pd.isna(r.get("bytes")) else f"{int(r['bytes'])}"
            out.append(f"{system} & {variant} & {profile} & {fmt_ci(r)} & {wire} \\\\")
    out += ["\\bottomrule", "\\end{tabular}"]
    return "\n".join(out) + "\n"


def table2(df: pd.DataFrame) -> str:
    components = [
        ("Layer 1: Mode A verify (aggregate)", "mode-a-verify-aggregate", {"escrow": "e0"}),
        ("Layer 1: Mode B verify ($L=8$)", "mode-b-verify",
         {"L": 8, "disclosure_fraction": 0.0, "escrow": "e0"}),
        ("Layer 3: escrow check, E1 (unsound)", "escrow-check", {"escrow": "e1"}),
        ("Layer 3: escrow check, E2 (sound)", "escrow-check", {"escrow": "e2"}),
        ("Revocation: R0 epoch check", "r0-epoch-check", {}),
        ("Revocation: R1 CRL, $|R|=10^6$", "r1-crl-hashset-miss", {"R": 1000000}),
        ("Revocation: R2 Bloom, $|R|=10^6$", "r2-bloom-miss", {"R": 1000000, "fp_target": 0.01}),
        ("Replay: nonce cache, $10^6$ entries", "nonce-cache-insert", {"entries": 1000000}),
    ]
    out = ["% Generated by analysis/gen_tables.py. Do not edit by hand.",
           "\\begin{tabular}{lll}", "\\toprule",
           "Component & Profile & Median (ms) [95\\% CI] \\\\", "\\midrule"]
    for label, name, cond in components:
        for profile, sub in df.groupby("profile"):
            hit = common.select(sub[sub["name"] == name], **cond)
            if hit.empty:
                continue
            out.append(f"{label} & {profile} & {fmt_ci(hit.iloc[0])} \\\\")
    out += ["\\bottomrule", "\\end{tabular}"]
    return "\n".join(out) + "\n"


def table_mode_b_sweep(df: pd.DataFrame) -> str:
    sub = df[(df["name"] == "mode-b-verify")].copy()
    if sub.empty:
        return "% no Mode B sweep measured\n"
    sub = common.select(sub, escrow="e0")
    sub["L"] = sub["L"].astype(int)
    sub["disclosure_fraction"] = sub["disclosure_fraction"].astype(float)
    out = ["% Generated by analysis/gen_tables.py. Do not edit by hand.",
           "\\begin{tabular}{lrrrr}", "\\toprule",
           "Profile & $L$ & Disclosed & Verify (ms) & Wire (B) \\\\", "\\midrule"]
    for (profile, l, frac), grp in sub.groupby(["profile", "L", "disclosure_fraction"]):
        r = grp.iloc[0]
        wire = "--" if pd.isna(r.get("bytes")) else f"{int(r['bytes'])}"
        out.append(f"{profile} & {l} & {frac * 100:.0f}\\% & {r['median_ms']:.3f} & {wire} \\\\")
    out += ["\\bottomrule", "\\end{tabular}"]
    return "\n".join(out) + "\n"


def table_headline(df: pd.DataFrame) -> str:
    """Every headline comparison, derived from the fastest measured variant.

    `HeadlineVariants.assert_uses_minimum` re-derives which Mode A variant is
    actually fastest and raises if this table pinned a slower one — the guard
    against silently re-introducing the aggregate-verifier figure, which is
    slower than the naive one for a single presentation.
    """
    lines = ["% Generated by analysis/gen_tables.py. Do not edit by hand.",
             "\\begin{tabular}{lll}", "\\toprule",
             "Quantity & Profile & Measured \\\\", "\\midrule"]
    for profile, sub in df.groupby("profile"):
        a_name, a_cond, a_ms = common.HeadlineVariants.fastest(sub, "mode-a")
        b_name, b_cond, b_ms = common.HeadlineVariants.fastest(sub, "mode-b")
        common.HeadlineVariants.assert_uses_minimum(sub, "mode-a", a_name)
        common.HeadlineVariants.assert_uses_minimum(sub, "mode-b", b_name)

        def med(name, **cond):
            hit = common.select(sub[sub["name"] == name], **cond)
            return None if hit.empty else float(hit.iloc[0]["median_ms"])

        def wire(name, **cond):
            hit = common.select(sub[sub["name"] == name], **cond)
            if hit.empty or pd.isna(hit.iloc[0].get("bytes")):
                return None
            return int(hit.iloc[0]["bytes"])

        variant = a_name.replace("mode-a-verify-", "")
        lines.append(
            f"Mode A headline variant & {profile} & {variant} "
            f"({common.sig3(a_ms)} ms) \\\\"
        )
        lines.append(
            f"Cost of issuer-unlinkability & {profile} & "
            f"${b_ms - a_ms:+.3f}$ ms (Mode B $-$ Mode A) \\\\"
        )

        cl = med("cl-rsa-verify", L=5, n_disclosed=0)
        if cl:
            lines.append(
                f"Speedup over CL-RSA, Mode A & {profile} & "
                f"{common.sig3(cl / a_ms)}$\\times$ \\\\"
            )
            lines.append(
                f"Speedup over CL-RSA, Mode B & {profile} & "
                f"{common.sig3(cl / b_ms)}$\\times$ \\\\"
            )

        scms = med("scms-implicit-verify")
        scms_b = wire("scms-implicit-verify")
        if scms:
            lines.append(
                f"Mode A vs SCMS-ECQV & {profile} & "
                f"{common.sig3(a_ms / scms)}$\\times$ slower \\\\"
            )
            b2_ms = med("mode-b-verify", L=8, disclosure_fraction=0.0, escrow="e2")
            b2_bytes = wire("mode-b-verify", L=8, disclosure_fraction=0.0, escrow="e2")
            if b2_ms and scms_b and b2_bytes:
                lines.append(
                    f"Mode B + E2 vs SCMS-ECQV & {profile} & "
                    f"{common.sig3(b2_ms / scms)}$\\times$ slower, "
                    f"{common.sig3(b2_bytes / scms_b)}$\\times$ larger \\\\"
                )

        e1 = med("escrow-check", escrow="e1")
        e2 = med("escrow-check", escrow="e2")
        if e1 is not None and e2 is not None:
            lines.append(
                f"Cost of a sound escrow proof & {profile} & "
                f"${e2 - e1:+.3f}$ ms (E2 $-$ E1) \\\\"
            )
    lines += ["\\bottomrule", "\\end{tabular}"]
    return "\n".join(lines) + "\n"


def main() -> int:
    df = common.bench_frame()
    common.write_tex("table1_mode_comparison.tex", table1(df))
    common.write_tex("table2_layer_breakdown.tex", table2(df))
    common.write_tex("table3_mode_b_sweep.tex", table_mode_b_sweep(df))
    common.write_tex("table_headline_answers.tex", table_headline(df))

    # The environment table comes from the metadata header, so it can never
    # drift from the machine the numbers were taken on.
    results = common.find_results("bench")
    rows = ["% Generated by analysis/gen_tables.py. Do not edit by hand.",
            "\\begin{tabular}{ll}", "\\toprule", "Property & Value \\\\", "\\midrule"]
    for res in results:
        m = res.meta
        e = common.tex_escape
        rows.append(f"\\multicolumn{{2}}{{l}}{{\\textbf{{Profile {e(res.label())}}}}} \\\\")
        rows.append(f"CPU & {e(m['cpu_model'])} \\\\")
        rows.append(f"Logical cores & {m['cpu_cores_logical']} \\\\")
        ram = m.get("ram_bytes")
        rows.append(f"RAM & {ram / 1024 ** 3:.1f} GiB \\\\" if ram else "RAM & -- \\\\")
        rows.append(f"OS / kernel & {e(m['os'])} / {e(m['kernel'])} \\\\")
        rows.append(f"Target triple & {e(m['target_triple'])} \\\\")
        rows.append(f"Toolchain & {e(m['rustc_version'])} \\\\")
        rows.append(f"Build & {e(m['build_profile'])}, opt {e(m['opt_level'])}, "
                    f"target-cpu {e(m['target_cpu'])} \\\\")
        rows.append(f"CPU governor & {e(m['cpu_governor'])} \\\\")
        rows.append(f"Commit & \\texttt{{{e(m['git_commit'])}}} \\\\")
        rows.append(f"Emulated & {'yes' if m['emulated'] else 'no'} \\\\")
        for name, version in m.get("crypto_crate_versions", []):
            rows.append(f"\\quad {e(name)} & {e(version)} \\\\")
        rows.append("\\midrule")
    rows += ["\\bottomrule", "\\end{tabular}"]
    common.write_tex("table_environment.tex", "\n".join(rows) + "\n")
    return 0


if __name__ == "__main__":
    sys.exit(main())
